services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vjm_website
    ports:
      - "8000:80"
    volumes:
      - ./website:/var/www/html
    restart: unless-stopped
